"use client";

import { useState, useEffect } from "react";
import { TextGenerateEffect } from "../../components/ui/text-generate-effect";
import StartChapter from "@/components/ui/startChapter";

const lessons = [
  "A very strange light was visible on the earthling sky. What was mistaken by a “guest star” it was indeed the supernova that originated this remarkable nebula",
  "In order to help understand the supernova remnant’s origins James Webb newly captured channels helped us to better identify the elements that compose the fragments of the past blast",
  "The Red components represent dust emissions not visible before. In Green is possible to identify the regions of doubly ionized sulfur that, when overlapped with dust, create yellow-white regions",
  "Lastly, in Blue, it’s possible to identify the  ghostly synchrotron emission generated by the neutron rotating star at the center of the nebula",
];

function CrabLessonChapter({ currentClickQtt }: { currentClickQtt: number }) {
  console.log("currentClickQtt", currentClickQtt);
  console.log("lessons[currentClickQtt - 1]", lessons[currentClickQtt - 1]);
  return (
    <div className="relative w-screen h-screen overflow-hidden">
      <img
        src="/crab/Full.jpg"
        alt="Fullscreen background image"
        className="absolute inset-0 w-full h-full object-cover"
      />
      <div className="absolute inset-0 flex items-end justify-center text-[#ECECEC]">
        <div className="w-full h-1/3 bg-gradient-to-t from-[rgba(0,0,0,0.8)] via-[rgba(0,0,0,0.5)] to-transparent flex items-end justify-center">
          <div className="text-center">
            <TextGenerateEffect words={lessons[currentClickQtt - 1]} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default function Page() {
  const [clickQtt, setClickQtt] = useState(0);
  const [lastClickTime, setLastClickTime] = useState(0);

  useEffect(() => {
    const handleClick = () => {
      const currentTime = Date.now();
      if (currentTime - lastClickTime >= 3000) {
        setClickQtt((prev) => prev + 1);
        setLastClickTime(currentTime);
        console.log("clickQtt", clickQtt);
      }
    };

    document.addEventListener("click", handleClick);

    return () => {
      document.removeEventListener("click", handleClick);
    };
  }, [lastClickTime]);

  return (
    <div onClick={() => setClickQtt(clickQtt)}>
      {clickQtt === 0 ? (
        <StartChapter chapterNumber="III" chapterTitle="CRAB NEBULA" />
      ) : clickQtt <= lessons.length ? (
        <CrabLessonChapter currentClickQtt={clickQtt} />
      ) : (
        <div className="text-center text-4xl text-[#ECECEC]">
          Some other text
        </div>
      )}
    </div>
  );
}
